CHDR = \


DHDR = \


SHDR = \


CSRC = \
testing_cpotrf_gpu.cpp testing_cgeqrf_gpu.cpp testing_cgetrf_gpu.cpp testing_cposv_gpu.cpp testing_cgesv_gpu.cpp testing_cgeqrs_gpu.cpp testing_cgemm.cpp

DSRC = \
testing_dpotrf_gpu.cpp testing_dgeqrf_gpu.cpp testing_dgetrf_gpu.cpp testing_dposv_gpu.cpp testing_dgesv_gpu.cpp testing_dgeqrs_gpu.cpp testing_dgemm.cpp

SSRC = \
testing_spotrf_gpu.cpp testing_sgeqrf_gpu.cpp testing_sgetrf_gpu.cpp testing_sposv_gpu.cpp testing_sgesv_gpu.cpp testing_sgeqrs_gpu.cpp testing_sgemm.cpp
